# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hashtag name')),
            ],
            options={
                'verbose_name_plural': 'Hashtags',
                'verbose_name': 'Hashtag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=100, verbose_name='Media ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='twitter_photos')),
                ('link', models.URLField(verbose_name='Link')),
                ('caption', models.TextField(blank=True, default='', null=True, verbose_name='Caption text')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter username')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='TwitterApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Application Name')),
                ('consumer_key', models.CharField(max_length=50, verbose_name='Twitter App consumer key')),
                ('consumer_secret', models.CharField(max_length=50, verbose_name='Twitter App consumer secret')),
                ('is_auto_access_token', models.BooleanField(default=True, verbose_name='Get access token automatically')),
                ('access_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Access token')),
                ('access_token_secret', models.CharField(blank=True, max_length=50, null=True, verbose_name='Access token secret')),
                ('tag_is_show', models.BooleanField(default=False, verbose_name='Show posts')),
            ],
            options={
                'verbose_name_plural': 'Twitter Applications',
                'verbose_name': 'Twitter Application',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_post', to='django_twitter_photo_api.TwitterApp'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='django_twitter_photo_api.Hashtag'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_hashtag', to='django_twitter_photo_api.TwitterApp'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('application', 'media_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together=set([('application', 'name')]),
        ),
    ]
